import Service from "@/containers/Service";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function ServicePage() {
  return (
    <main>
        <Service />
    </main>
  );
}