import Calculator from "@/containers/Calculator";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function СalculatorPage() {
  return (
    <main>
        <Calculator/>
    </main>
  );
}