import TitleBox from "@/components/UI/titleBox/TitleBox";
import BreadCrumbs from "@/components/UI/breadCrumbs/BreadCrumbs";
import cl from "@blog/blog.module.scss";
import BlogPanel from "@/containers/blog/BlogPanel";

export const metadata = {
  title: "Блог Градус Хаус",
  description: "Generated by create next app",
};

function getBreadCrumbs() {
  return [
    { name: "Главная", href: "/" },
    { name: "Блог", href: "/blog" },
  ];
}

export default async function BlogPage() {
  const breadCrumbsItems = getBreadCrumbs();
  return (
    <main className={cl.blog}>
      <div className="container">
        <BreadCrumbs breadCrumbsItems={breadCrumbsItems} />
        <TitleBox>Блог</TitleBox>
        <BlogPanel />
      </div>
    </main>
  );
}
