import Account from "@/containers/account/Account";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function AccountPage() {
  return (
    <main>
        <Account/>
    </main>
  );
}