import ProductsNew from "@/containers/main/ProductsNew";
import Hero from "../containers/main/hero/Hero";
import Features from "@/containers/main/Features";
import Blogs from "@/containers/main/Blogs";
import Brands from "@/containers/main/Brands";
import VideoBlock from "@/containers/main/VideoBlock";
import Categories from "../containers/main/Categories";
import Cooperation from "@/containers/main/cooperation/Cooperation";
import TagsBlock from "../containers/main/TagsBlock";
import ProductsPopular from "../containers/main/ProductsPopular";
import Offers from "../containers/main/Offers";
import { getApiData } from "@/api/getData";

export const metadata = {
  title: "Title",
  description: "Generated by create next app",
};
export default async function Main() {
  const productsNew = await getApiData("products?collection=new");
  const productsPopualar = await getApiData("products?collection=popular");
  const brands = await getApiData("brands");
  const categories = await getApiData("rubrics?collection=categories");
  return (
    <main>
      <Hero />
      <ProductsNew products={productsNew} />
      <Offers />
      <ProductsPopular products={productsPopualar} />
      <Categories categories={categories} />
      <TagsBlock />
      <Blogs />
      <Brands brands={brands} />
      <VideoBlock />
      <Features />
      <Cooperation />
    </main>
  );
}
