import styles from "@blogOne/blogeOne-page.module.scss";
import Content from "@/containers/blogOne/Content";
import ProductsBlock from "@/containers/blogOne/ProductsBlog";
import TitleBox from "@/components/UI/titleBox/TitleBox";
import BreadCrumbs from "@/components/UI/breadCrumbs/BreadCrumbs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getBreadCrumbs() {
  return [
    { name: "Главная", href: "/" },
    { name: "Блог", href: "/blog" },
    { name: "Рецепт российского сыра", href: "/recipe" },
  ];
}

export default async function BlogOnePage() {
  const breadCrumbsItems = getBreadCrumbs();

  return (
    <main className={styles.main}>
      <div className="container">
        <BreadCrumbs breadCrumbsItems={breadCrumbsItems} />
        <TitleBox classItem={styles.title}>Рецепт российского сыра</TitleBox>
      </div>
      <Content />
      <ProductsBlock />
    </main>
  );
}
