import PopularProducts from "@/containers/subCatalog/PopularProducts";
import ProductsBlock from "@/containers/subCatalog/ProductsBlock";
import TagsBlock from "@/containers/subCatalog/TagsBlock";
import { getApiData } from "@/api/getData";
type Props = {
  params: {
    subcatalog: string;
  };
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function SubcatalogPage({
  params: { subcatalog },
}: Props) {
  return (
    <main>
      <TagsBlock />
      <ProductsBlock />
      <PopularProducts />
    </main>
  );
}
