import cl from "@product/product-page.module.scss";
import BreadCrumbs from "@/components/UI/breadCrumbs/BreadCrumbs";
import BuyerPhotos from "@/containers/product/BuyerPhotos";
import ProductSlider from "@/containers/product/ProductSlider";
import ProductHead from "@/containers/product/ProductHead";
import About from "@/containers/product/About";
import Kit from "@/containers/product/Kit";
import SimilarProducts from "@/containers/product/SimilarProducts";
import AdditionalProducts from "@/containers/product/AdditionalProducts";
import Reviews from "@/containers/product/Reviews";
import ProductTabs from "@/containers/product/ProductTabs";
import ProductDescription from "@/containers/product/ProductDescription";
import ProductDetails from "@/containers/product/ProductDetails";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  params: {
    product: string;
  };
};

function getBreadCrumbs(productName: string) {
  return [
    { name: "Главная", href: "/" },
    { name: "Каталог", href: "#main-catalog" },
    { name: "Самогоноварение", href: "/samogonovarenie" },
    {
      name: "Самогоннные аппараты",
      href: "/samogonovarenie/samogonovarenie-apparaty",
    },
    {
      name: "productName",
      href: "/samogonovarenie/samogonovarenie-apparaty/" + productName,
    },
  ];
}

export default function ProductPage({ params: { product } }: Props) {
  const breadCrumbsItems = getBreadCrumbs(product);
  return (
    <main className={cl.main}>
      <div className="container">
        <BreadCrumbs breadCrumbsItems={breadCrumbsItems} />
        <div className={cl.layout}>
          <ProductSlider />
          <ProductHead />
          <ProductTabs />
          <ProductDescription />
          <ProductDetails />
          <BuyerPhotos />
          <About />
          <Kit />
        </div>
      </div>
      <SimilarProducts />
      <AdditionalProducts />
      <Reviews />
    </main>
  );
}
