import BasketForm from "@/containers/basket/BasketForm";
import cl from "@basket/basket.module.scss";
import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function BasketPage() {
  return (
    <main className={cl.basket}>
      <div className="container">
        <Link href="/" className={cl.linkBack}>
          &lt;&lt; Назад к покупкам
        </Link>
      </div>
      <BasketForm />
    </main>
  );
}
