import styles from "@catalog/catalog-page.module.scss";
import VideoBlock from "@/containers/catalog/VideoBlock";
import Categories from "@/containers/catalog/Categories";
import Blogs from "@/containers/catalog/Blogs";
import ProductsPopular from "@/containers/catalog/ProductsPopular";
import TagsBlock from "@/containers/catalog/TagsBlock";
import { getApiData } from "@/api/getData";
import BreadCrumbs from "@/components/UI/breadCrumbs/BreadCrumbs";
import TitleBox from "@/components/UI/titleBox/TitleBox";
import NotFound from "@/containers/NotFound";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  params: {
    catalog: string;
  };
};

function getBreadCrumbs(brand: string, slug: string) {
  return [
    { name: "Главная", href: "/" },
    { name: "Каталог", href: "#main-catalog" },
    { name: "Самогоноварение", href: `/${slug}` },
  ];
}

export default async function CatalogPage({ params: { catalog } }: Props) {
  const rubric = await getApiData(`rubrics?collection=sub-rubrics-${catalog}`);

  const products = await getApiData(`products?collection=popular-${catalog}`);
  const breadCrumbsItems = getBreadCrumbs("", catalog);

  if (!rubric.data.length) {
    return <NotFound />;
  }

  return (
    <main className={styles.main}>
      <div className="container">
        <BreadCrumbs
          classItem={styles.bread}
          breadCrumbsItems={breadCrumbsItems}
        />
        <TitleBox classItem={styles.title}>Самогоноварение</TitleBox>
      </div>
      <Categories rubric={rubric} />
      <TagsBlock />
      <ProductsPopular products={products} />
      <Blogs />
      <VideoBlock />
    </main>
  );
}
